task:
  name: mysql-backup
  descriptionZh: |
    备份 mysql 数据库
  descriptionEn: |
    Backup mysql database
  script: |
    BACKUP_FILE_NAME=${CONTAINER_NAME}_$(date +"%Y%m%d%H%M%S").sql
    docker exec ${CONTAINER_NAME} mysqldump -u root -p${MYSQL_ROOT_PASSWORD} --all-databases > ${BACKUP_TARGET_PATH%/}/${BACKUP_FILE_NAME}
    echo "✅ 备份完成，备份文件位于: ${BACKUP_TARGET_PATH%/}/${BACKUP_FILE_NAME}"
  tag:
    - dpanel
    - run-in-dpanel
  environment:
    - name: CONTAINER_NAME
      labelZh: 需要备份的 mysql 数据库容器名称
      labelEn: backup container name of mysql
    - name: MYSQL_ROOT_PASSWORD
      labelZh: mysql 的 root 密码
      labelEn: root password
    - name: BACKUP_TARGET_PATH
      labelZh: 备份到宿主机的目录
      labelEn: backup target path of host