task:
  name: container-backup
  descriptionZh: |
    生成容器快照，支持备份容器配置存储，一键恢复。
  descriptionEn: |
    Create container snapshot
  script: |
    /app/server/dpanel container:backup -f /app/server/config.yaml --name=${CONTAINER_NAME} --enable-image ${ENABLE_IMAGE}
  tag:
    - dpanel
    - run-in-dpanel
  environment:
    - name: CONTAINER_NAME
      labelZh: 容器名称
      labelEn: container name
      required: true
    - name: ENABLE_IMAGE
      labelZh: 是否备份容器镜像
      required: true
      labelEn: backup container image
      type: select
      values:
        - label: 是
          value: "1"
        - label: 否
          value: "0"