task:
  name: container-backup
  descriptionZh: |
    备份容器中存储卷或是挂载目录
  descriptionEn: |
    Backup the mount directory or volume in the container
  script: |
    BACKUP_FILE_NAME=${CONTAINER_NAME}_$(date +"%Y%m%d%H%M%S").tar
    BACKUP_CONTAINER_PATH=$(docker inspect ${CONTAINER_NAME} --format '{{range .Mounts}}{{.Destination}} {{end}}')
    echo "备份目录为 ${BACKUP_PATH}"
    docker run -i --rm --name dpanel-task-backup \
    --volumes-from ${CONTAINER_NAME} \
    -v ${BACKUP_PATH}:/backup busybox \
    tar czvf /backup/${BACKUP_FILE_NAME} ${BACKUP_CONTAINER_PATH}
    echo "备份完成，备份文件位于: ${BACKUP_PATH}/${BACKUP_FILE_NAME}"
  tag:
    - dpanel
    - run-in-dpanel
  environment:
    - name: CONTAINER_NAME
      labelZh: 容器名称
      labelEn: container name
    - name: BACKUP_PATH
      labelZh: 备份到主机目录
      labelEn: host backup path