name: Download and Release Toolchains

on:
  workflow_dispatch:  # 仅手动触发

jobs:
  download_toolchains:
    runs-on: ubuntu-latest
    steps:
      - name: Download GNU Toolchains
        run: |
          mkdir -p toolchains
          cd toolchains
          curl -Lo arm64.tar.xz https://developer.arm.com/-/media/Files/downloads/gnu/13.3.rel1/binrel/arm-gnu-toolchain-13.3.rel1-x86_64-aarch64-none-linux-gnu.tar.xz
          curl -Lo arm.tar.xz https://developer.arm.com/-/media/Files/downloads/gnu/13.3.rel1/binrel/arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-linux-gnueabihf.tar.xz
      - name: Download Musl Toolchains
        run: |
          cd toolchains
          curl -Lo amd64-musl.tgz https://musl.cc/x86_64-linux-musl-cross.tgz
          curl -Lo arm64-musl.tgz https://musl.cc/aarch64-linux-musl-cross.tgz
          curl -Lo arm-musl.tgz https://musl.cc/arm-linux-musleabihf-cross.tgz
      - name: Download Synology Toolchains
        run: |
          cd toolchains
          curl -Lo armv8-synology.txz https://global.synologydownload.com/download/ToolChain/toolchain/7.1-42661/Realtek%20RTD129x%20Linux%204.4.180/rtd1296-gcc850_glibc226_armv8-GPL.txz 
          curl -Lo amd64-synology.txz https://global.synologydownload.com/download/ToolChain/toolchain/7.1-42661/Intel%20x86%20Linux%204.4.180%20%28GeminiLake%29/geminilake-gcc850_glibc226_x86_64-GPL.txz
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: toolchains-v1
          name: "Toolchains Collection"
          body: "Pre-built toolchains for ARM, ARM64, AMD64 and Synology platforms"
          files: |
            toolchains/arm64.tar.xz
            toolchains/arm.tar.xz
            toolchains/amd64-musl.tgz
            toolchains/arm64-musl.tgz
            toolchains/arm-musl.tgz
            toolchains/armv8-synology.txz
            toolchains/amd64-synology.txz
          draft: false
          prerelease: false
