name: release
on:
  push:
    tags:
    - 'v*'
jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        go-version: [ '1.22' ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: test env
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
          echo "Tag name from github.ref: ${{  github.ref }}"
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: |
          go get .
      - name: Build
        run: |
          make build PROJECT_NAME=dpanel-amd64 CGO_ENABLED=1
          
          # arm64
          curl -Lo arm64.tar.xz https://developer.arm.com/-/media/Files/downloads/gnu/13.3.rel1/binrel/arm-gnu-toolchain-13.3.rel1-x86_64-aarch64-none-linux-gnu.tar.xz
          mkdir ./arm64 && tar -xvf arm64.tar.xz --strip-components=1 -C ./arm64
          make build PROJECT_NAME=dpanel-arm64 CGO_ENABLED=1 GOARM=7 GOARCH=arm64 GOOS=linux \
          CC=${PWD}/arm64/bin/aarch64-unknown-linux-gnu-gcc CXX=${PWD}/arm64/bin/aarch64-unknown-linux-gnu-g++
          rm -rf arm64.tar.xz arm64

          # armv7
          curl -Lo arm.tar.xz https://developer.arm.com/-/media/Files/downloads/gnu/13.3.rel1/binrel/arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-linux-gnueabihf.tar.xz
          mkdir ./arm && tar -xvf arm.tar.xz --strip-components=1 -C ./arm
          make build PROJECT_NAME=dpanel-arm CGO_ENABLED=1 GOARM=7 GOARCH=arm GOOS=linux \
          CC=${PWD}/arm/bin/arm-none-linux-gnueabihf-gcc CXX=${PWD}/arm/bin/arm-none-linux-gnueabihf-g++
          rm -rf arm.tar.xz arm

          # 群辉 arm64
          curl -Lo synology-arm64.txz https://global.synologydownload.com/download/ToolChain/toolchain/7.1-42661/Realtek%20RTD129x%20Linux%204.4.180/rtd1296-gcc850_glibc226_armv8-GPL.txz
          mkdir ./synology-arm64 && tar -Jvxf synology-arm64.txz --strip-components=1 -C ./synology-arm64
          make build PROJECT_NAME=dpanel-synology-arm64 CGO_ENABLED=1 GOARM=7 GOARCH=arm64 GOOS=linux \
          CC=${PWD}/synology-arm64/bin/aarch64-unknown-linux-gnu-gcc CXX=${PWD}/synology-arm64/bin/aarch64-unknown-linux-gnu-g++
          rm -rf synology-arm64.txz synology-arm64

          # 群辉 amd64
          curl -Lo synology-amd64.txz https://global.synologydownload.com/download/ToolChain/toolchain/7.1-42661/Intel%20x86%20Linux%204.4.180%20%28GeminiLake%29/geminilake-gcc850_glibc226_x86_64-GPL.txz
          mkdir ./synology-amd64 && tar -Jvxf synology-amd64.txz --strip-components=1 -C ./synology-amd64
          make build PROJECT_NAME=dpanel-synologty-amd64 CGO_ENABLED=1 GOARCH=amd64 GOOS=linux \
          CC=${PWD}/synology-amd64/bin/x86_64-pc-linux-gnu-gcc CXX=${PWD}/synology-amd64/bin/x86_64-pc-linux-gnu-g++
          rm -rf synology-amd64.txz synology-amd64
      - name: create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          body: TODO New Release.
          prerelease: false
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          tag_name: ${{ github.ref_name }}
          files: runtime/*
          prerelease: false